name: Build Thesis PDF v2

on: [push]

jobs:
  build_pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build PDF
      uses: xu-cheng/latex-action@v2
      with:
        root_file: thesis.tex

    - name: Archive PDF
      uses: actions/upload-artifact@v3
      with:
        name: "thesis_$(date +'%Y-%m-%d_%H-%M-%S').pdf"


        path: thesis.pdf
